### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by Talanor** [Talanor/findmyhash#6]
If hash cracking fails because the given online service is down or because its syntax has changed, report it with a procedure (and disable it in the service list)

**Comment by dheerajkumarpatel** [comment]
not open show error 
Traceback (most recent call last):
  File "/home/kalikali/findmyhash/hash-tool.py", line 9, in <module>
    from findmyhash import services
  File "/home/kalikali/findmyhash/findmyhash/services/__init__.py", line 1, in <module>
    from . import (
  File "/home/kalikali/findmyhash/findmyhash/services/MD5Hashing.py", line 5, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
